use_frameworks!

platform :ios, '10.0'

target 'zys2007_Example' do
  pod 'zys2007', :path => '../'

  target 'zys2007_Tests' do
    inherit! :search_paths

  pod 'AFNetworking'                  #网络加载

  end
end
